// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class processorsfix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(processorsfix2));
        
        string IMigrationMetadata.Id
        {
            get { return "201406061500159_processors-fix-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
