// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deriver2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deriver2));
        
        string IMigrationMetadata.Id
        {
            get { return "201403242001047_deriver2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
