// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class colorcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(colorcode));
        
        string IMigrationMetadata.Id
        {
            get { return "201404102037294_color-code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
