// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class readdedbuilder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdedbuilder));
        
        string IMigrationMetadata.Id
        {
            get { return "201402072211100_re-added-builder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
