// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class takeitback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(takeitback));
        
        string IMigrationMetadata.Id
        {
            get { return "201403242105448_takeitback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
