// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class grids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grids));
        
        string IMigrationMetadata.Id
        {
            get { return "201402071904158_grids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
