// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class builder_log_has_optional_builder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(builder_log_has_optional_builder));
        
        string IMigrationMetadata.Id
        {
            get { return "201403061559058_builder_log_has_optional_builder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
