// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class value1112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(value1112));
        
        string IMigrationMetadata.Id
        {
            get { return "201404110232382_value11-12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
