// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class stepsinday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stepsinday));
        
        string IMigrationMetadata.Id
        {
            get { return "201404171438172_stepsinday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
