// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class something1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(something1));
        
        string IMigrationMetadata.Id
        {
            get { return "201404011802310_something1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
