// <auto-generated />
namespace JassWeather.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fix_processor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_processor));
        
        string IMigrationMetadata.Id
        {
            get { return "201406061426172_fix_processor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
